NestJs with monorepo serverless-architecture & CT Client service
jjtech-digital/nest-ct-mono-repo pull request #3
Opened 2024-05-07 05:20 UTC by Yash-D-composeTech

2024-05-11 04:12 UTC, 0xakuma requested changes

2024-05-11 04:12 UTC, 0xakuma commented on nest-commercetools-project/apps/auth-app/src/auth-app.controller.ts
> +  getTotalCustomers(): Promise<object> {
Can we avoid object type, we can use CT types

2024-05-11 04:12 UTC, 0xakuma commented on nest-commercetools-project/apps/auth-app/src/main.ts
> +  // const expressApp = app.getHttpAdapter().getInstance();
remove comments if not needed

2024-05-11 04:12 UTC, 0xakuma commented on nest-commercetools-project/apps/product-app/src/product-app.controller.ts
> +  getTotalProducts(): Promise<object> {
Use CT types

2024-05-11 04:12 UTC, 0xakuma commented on nest-commercetools-project/libs/common/src/ctClient/ctClient.services.ts
> +    this.scope = `manage_project:${this.CT_PROJECT_KEY}`;
Should we use this scope for CT client ?

2024-05-16 03:27 UTC, Yash-D-composeTech commented on nest-commercetools-project/libs/common/src/ctClient/ctClient.services.ts
> +    this.scope = `manage_project:${this.CT_PROJECT_KEY}`;
In my CT demo account I have created a demo client with manage_project scope That's why declare that scope for CT client. In future we can update it as per requirement
![image](https://github.com/jjtech-digital/nest-ct-mono-repo/assets/168187470/8f0272b9-2f36-4709-b3a6-82ace1efbf7d)

2024-05-16 03:39 UTC, 0xakuma approved these changes

2024-05-16 04:03 UTC, merged